packaged/objects/Engaged_Couple__c.object
<CustomObject>
    <fields>
        <fullName>Passcode__c</fullName>
        <inlineHelpText>Passcode that WTL Coordinators use to update Engaged Couple records in FormAssembly form.</inlineHelpText>
        <label>Passcode</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Engaged Couple</label>
    <nameField>
        <label>Engaged Couple</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engaged Couples</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestGeneratePasscode.cls
@isTest
private class TestGeneratePasscode {
    @isTest static void TestCreateEngagedCouple() {
        // Test passcode for new Engaged Couples
        // Create a new Engaged Couple, perform test
        Test.startTest();
        Engaged_Couple__c ec = new Engaged_Couple__c (Name='test couple');
        insert ec;
        Test.stopTest();
        
        // verify
        // a passcode should have been generated
        System.assert(ec.Passcode__c != 'null');
           
    }

}